apiVersion: v1
kind: Service
metadata:
  name: cats-dogs-api
  labels:
    app: cats-dogs-api
spec:
  type: LoadBalancer
  selector:
    app: cats-dogs-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000
  sessionAffinity: None
